apiVersion: v1
kind: Service
metadata:
  name: infraops-automator-svc
spec:
  type: NodePort
  selector:
    app: infraops-automator
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
